import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";

const makan = localFont({
    src: "../public/fonts/MakanHatiCyrillic.woff",
    variable: "--font-makan",
    weight: "400",
    style: "normal",
    display: "swap",

});


export const metadata: Metadata = {
    title: "TimmyDev",
    description: "Generated by create next app",
};

export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <html lang="en" className={makan.className}>
        <body>{children}</body>
        </html>
    );
}